OPCODES = {
    2: 'CONCAT',
    4: 'CALL_VARARG',
    6: 'MUL',
    8: 'SUB',
    10: 'POW',
    12: 'TEST_JMP_FALSE',
    14: 'TAILCALL_COPY',
    17: 'SETTABLE_CONST',
    19: 'CLOSE_UPVALS',
    21: 'LOADK_D',
    23: 'ADD_IMM',
    25: 'LOADK_L',
    27: 'JMP_IF_NE',
    29: 'JMP_IF_NE_2',
    32: 'SETLIST',
    34: 'MUL_IMM',
    36: 'CLOSE_UPVALS_2',
    38: 'ADD',
    40: 'SUB_REV',
    42: 'CALL_2ARG',
    44: 'SETTABLE',
    46: 'CLOSE_UPVALS_3',
    48: 'GETTABLE_CONST',
    50: 'SETTABLE_UPVAL',
    52: 'SETTABLE_CONST_2',
    54: 'CALL_FRAME_SETUP',
    56: 'MOD',
    58: 'LOADK',
    60: 'EQ',
    63: 'ADD_2',
    65: 'POW_IMM',
    67: 'SETTABLE_UPVAL_2',
    69: 'NOT',
    71: 'CLOSE_UPVALS_4',
    73: 'CALL_1ARG',
    75: 'SETTABLE_IMM',
    78: 'TAILCALL_COPY_2',
    80: 'MUL_IMM_2',
    82: 'LE',
    84: 'SUB_IMM',
    86: 'RETURN_RESTORE',
    88: 'LEN',
    90: 'LOADNIL',
    93: 'SETUPVAL',
    95: 'GETTABLE',
    97: 'SETTABLE_IMM_2',
    99: 'TEST_JMP_TRUE',
    101: 'MOVE',
    103: 'JMP_IF_GT',
    105: 'LOADCLOSURE',
    107: 'SELFCALL_0ARG',
    109: 'SETTABLE_UPVAL_3',
    111: 'LT',
    113: 'GETTABLE_UPVAL',
    115: 'EQ_IMM',
    117: 'GETTABLE_2',
    119: 'JMP',
    121: 'MOD_IMM',
}

FIELD_MAP = {
    'r': 'Fp[1]',
    'x': 'Fp[2]',
    'S': 'Fp[5]',
    'w': 'Fp[10]',
    'G': 'Fp[9]',
    'lp': 'Fp[7]',
    'l': 'Fp[8]',
    'Hp': 'Fp[11]',
    'E': 'Fp[4]',
}


def mnemonic(opcode):
    return OPCODES.get(opcode, f'UNKNOWN_{opcode}')
